name: Go tests

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 1.12, 1.13, 1.14 ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.version }}
      id: go

    - name: Get dependencies
      run: go mod download

    - name: Test
      run: go test ./...
